package com.thothassistant.stepdaddy.gateway.upstream

/** Name → iptv-org channel id aliases (parity with Linux logo_resolver.py). */
object LogoNameAliases {
    private val aliases: Map<String, String> = mapOf(
        "6ter france" to "6ter.fr",
        "a spor turkey" to "ASpor.tr",
        "a sport pk" to "ASport.pk",
        "abc ny" to "WABC-DT.us_locals1",
        "acc network" to "ACCNetwork.us",
        "ahc american heroes channel" to "AmericanHeroesChannel.us",
        "antenna tv usa" to "AntennaTV.us",
        "arte france" to "ARTE.fr",
        "atv turkey" to "ATV.tr",
        "azteca 7 mx" to "Azteca7.mx",
        "azteca uno mx" to "AztecaUno.mx",
        "bandsports" to "BandSports.br",
        "bandsports brasil" to "BandSports.br",
        "barca tv spain" to "BarcaTV.es",
        "bbc america bbca" to "BBCAmerica.us",
        "bbc news channel" to "BBCNews.uk",
        "bbc one" to "BBCOne.uk",
        "bein sports en espanol" to "beINSportsenEspanol.qa",
        "bein sports hd qatar" to "beINSports1.qa",
        "bein sports mena english 1" to "beIN.Sports.HD.ae",
        "bein sports usa" to "beINSportsUSA.us",
        "bein sports mena english 2" to "beIN.Sports.News.ae",
        "bfm tv france" to "BFMTV.fr",
        "big ten network btn usa" to "BigTenNetwork.us",
        "bnt 1 bulgaria" to "BNT1.bg",
        "bnt 2 bulgaria" to "BNT2.bg",
        "bnt 3 bulgaria" to "BNT3.bg",
        "btv lady bulgaria" to "bTVLady.bg",
        "c8 france" to "C8.fr",
        "canal 9 denmark" to "CANAL9.dk",
        "canal foot france" to "CanalFoot.fr",
        "canal motogp france" to "CanalMotoGP.fr",
        "cbs sports golazo" to "CBS Sports Golazo Network.us",
        "cbs sports network cbssn" to "CBSSportsNetworkUSA.us",
        "cbsny" to "WCBS-DT.us_locals1",
        "cbsny usa" to "WCBS-DT.us_locals1",
        "channel 10 israe" to "Channel10.il",
        "channel 14 israel" to "Channel14.il",
        "cmtv portugal" to "CMTV.pt",
        "cnews france" to "CNews.fr",
        "cnn" to "CNN.us",
        "combate brasil" to "Combate.br",
        "ct sport cz" to "CTSport.cz",
        "ctv 2 canada" to "CTV.Two.-.Toronto.ca2",
        "cw philly" to "WPSG-DT.us_locals1",
        "cw pix 11" to "WPIX-DT.us_locals1",
        "dazn 1 bar de" to "DAZN1.de",
        "dazn 2 bar de" to "DAZN2.de",
        "dazn ligue 1 france" to "DAZNLigue1.fr",
        "diema bulgaria" to "Diema.bg",
        "diema family bulgaria" to "DiemaFamily.bg",
        "discovery velocity ca" to "DiscoveryVelocity.ca",
        "dr1 denmark" to "DR1.dk",
        "dr2 denmark" to "DR2.dk",
        "dstv kyknet and kie" to "KykNET.&amp;.Kie.HD.za",
        "dstv m net" to "M-Net.HD.za",
        "dstv mzansi magic" to "Mzansi.Magic.HD.za",
        "eleven sports 5 portugal" to "ElevenSports5.pt",
        "ert 1 greece" to "ERT1.gr",
        "espn" to "ESPN.us",
        "espn premium argentina" to "ESPNPremium.ar",
        "espn2" to "ESPN2.us",
        "fanduel sports network arizona" to "FanDuel.Sports.Network.us",
        "fanduel sports network new orleans" to "FanDuel.Sports.New.Orleans.us",
        "fox sports 1" to "FoxSports1.us",
        "fox sports 2" to "FoxSports2.us",
        "foxny" to "WNYW-DT.us_locals1",
        "foxny usa" to "WNYW-DT.us_locals1",
        "galavisi n" to "Galavision.Cable.Network.HD.us2",
        "galavision" to "Galavision.Cable.Network.HD.us2",
        "hallmark channel" to "Hallmark.Channel.HD.us2",
        "hot3 israel" to "HOT3.il",
        "laliga smartbank tv" to "M+.LALIGA.TV.es",
        "law crime network" to "LawAndCrime.us",
        "lifetime movies network" to "Lifetime.HD.us2",
        "lifetime network" to "Lifetime.HD.us2",
        "liverpool" to "LFCTV.HD.uk",
        "liverpool tv lfc tv" to "LFCTV.HD.uk",
        "m4 sports hungary" to "M4.Sport.hu",
        "match football 1 russia" to "match futbol 1.ru",
        "match football 2 russia" to "match futbol 2.ru",
        "match football 3 russia" to "match futbol 3.ru",
        "match premier russia" to "match premer.ru",
        "match tv russia" to "telekanal match tv.ru",
        "mgm epix" to "MGM+.HD.us2",
        "mgm usa epix" to "MGM+.HD.us2",
        "movistar deportes 3 spain" to "M+.Deportes.3.es",
        "movistar deportes 4 spain" to "M+.Deportes.4.es",
        "movistar supercopa de espana" to "M+.Copa.del.Rey.es",
        "movistar supercopa de españa" to "M+.Copa.del.Rey.es",
        "mundotoro tv spain" to "MundotoroTV.es",
        "my9tv" to "WWOR-DT.us_locals1",
        "my9tv usa" to "WWOR-DT.us_locals1",
        "nat geo wild usa" to "NatGeoWild.us",
        "nbc" to "NBC.us",
        "nbc 10 philadelphia" to "WCAU-DT.us_locals1",
        "nbcny" to "WNBC-DT.us_locals1",
        "nbcny usa" to "WNBC-DT.us_locals1",
        "oneplay md 2 cz" to "OnePlayMD2.cz",
        "oneplay md 3 cz" to "OnePlayMD3.cz",
        "oneplay md 4 cz" to "OnePlayMD4.cz",
        "orange sport 1 romania" to "OrangeSport1.ro",
        "pdc tv" to "PDCTV.uk",
        "premier brasil" to "Premiere.Clubes.br",
        "premiere clubes" to "Premiere.Clubes.br",
        "racer tv usa" to "RacerTV.us",
        "rds ca" to "RDS.ca",
        "rds info ca" to "RDSInfo.ca",
        "rte 1" to "RTE.One.HD.ie",
        "rtl7 netherland" to "RTL7.nl",
        "showtime shoxbet usa" to "Paramount+.with.Showtime.HD.us2",
        "sky sports action" to "SkySportsNFL.uk",
        "sky sports f1" to "SkySportsF1.uk",
        "sky sports main event" to "SkySportsMainEvent.uk",
        "sky sports plus" to "SkySportsPlus.uk",
        "sky sports premier league" to "SkySportsPremierLeague.uk",
        "sky calcio 1 italy" to "Sky.Sport..251.it",
        "sky calcio 2 italy" to "Sky.Sport..252.it",
        "sky calcio 3 italy" to "Sky.Sport..253.it",
        "sky calcio 4 italy" to "Sky.Sport..254.it",
        "sport 5 star israel" to "Sport 5 Stars.il",
        "sport klub 1 croatia" to "SportKlub1.rs",
        "sport klub 2 croatia" to "SportKlub2.rs",
        "sport klub 3 croatia" to "SportKlub3.rs",
        "sport klub 4 croatia" to "SportKlub4.rs",
        "sport klub golf croatia" to "SportKlubGolf.rs",
        "sportdigital1 germany" to "Sportdigital1+.ch",
        "sportdigital1 plus germany" to "Sportdigital1+.ch",
        "sportv" to "SporTV.br",
        "sportv brasil" to "SporTV.br",
        "sportv2 brasil" to "SporTV2.br",
        "sportv3 brasil" to "SporTV3.br",
        "starzplay criclife 1 hd" to "CricLife1.in",
        "t sports bd" to "TSports.bd",
        "ten sports pk" to "TenSports.pk",
        "tennis 10" to "Tennis+.10",
        "tennis 12" to "Tennis+.12",
        "the hallmark channel" to "Hallmark.Channel.HD.us2",
        "tn live cz" to "TNLive.cz",
        "tnt" to "TNT.us",
        "tnt brasil" to "TNT.br",
        "tnt sports argentina" to "TNTSports.ar",
        "tnt sports hd chile" to "TNTSports.cl",
        "tv2 bornholm denmark" to "TV2Bornholm.dk",
        "tv4 football sweden" to "[SPORTK].TV4.Sportkanalen.se",
        "tve la 1 spain" to "TVELa1.es",
        "tve la 2 spain" to "TVELa2.es",
        "tvland" to "TV.Land.HD.us2",
        "veronica nl netherland" to "Veronica.cz",
        "vodafone sport" to "VodafoneSport.pt",
        "voyo special 1 sk" to "VoyoSpecial1.sk",
        "voyo special 2 sk" to "VoyoSpecial2.sk",
        "voyo special 3 sk" to "VoyoSpecial3.sk",
        "voyo special 4 sk" to "VoyoSpecial4.sk",
        "voyo special 7 sk" to "VoyoSpecial7.sk",
        "voyo special 8 sk" to "VoyoSpecial8.sk",
        "voyo special 9 sk" to "VoyoSpecial9.sk",
        "vtv plus uruguay" to "VTV+.HD.uy",
        "wetv usa" to "WeTV.us",
        "win sports columbia" to "Win.Sports.co",
        "win sports plus columbia" to "Win.Sports+.co",
        "yes movies action israel" to "YesMoviesAction.il",
        "yes movies comedy israel" to "YesMoviesComedy.il",
        "yes movies kids israel" to "YesMoviesKids.il",
        "yes tv ca" to "YesTV.ca",
        "матч! боец russia" to "match boets.ru",
    )

    fun lookup(name: String, norm: String?): String? {
        val keys = aliasLookupKeys(name, norm)
        for (key in keys) {
            aliases[key]?.let { return it }
        }
        return null
    }

    private fun aliasLookupKeys(name: String, norm: String?): List<String> {
        val raw = fixMojibake(name.lowercase().trim())
        val out = linkedSetOf<String>()
        for (candidate in listOf(raw, norm.orEmpty(), if (norm != null) "$norm usa" else "")) {
            val c = candidate.trim()
            if (c.isNotEmpty()) out += c
        }
        return out.toList()
    }

    private fun fixMojibake(name: String): String {
        var s = name.replace("�", "")
        for ((bad, good) in listOf(
            "贸" to "ó", "Ã³" to "ó", "Ã±" to "ñ", "Ã©" to "é", "贸" to "",
        )) {
            s = s.replace(bad, good)
        }
        return s
    }
}
